### ISSUE TITLE
Automatic module names

### ISSUE THREAD

**Issue by dmlloyd** [smallrye/smallrye-certificate-generator#31]
This is a request to add automatic module names for each module in this project. Part of the reason is to avoid problems due to one of the artifacts containing `private` in its name.

My suggestions for automatic module names are based on the root-most common package (which might be too general):

* `certificate-generator-junit5` -> `io.smallrye.certs.junit5`
* `certificate-generator-maven-plugin` -> `io.smallrye.certs.maven`
* `certificate-generator` -> `io.smallrye.certs` <- is this one too general?
* `private-key-pem-parser` -> `io.smallrye.certs.pem`

**Comment by cescoffier** [comment]
certificate-generator -> io.smallrye.certs.generator maybe?

For the pem one, it's only for private keys. Not sure how to capture this, without using 'private'

**Comment by dmlloyd** [comment]
How about `io.smallrye.certs.pem.private_keys` or something like that?

**Comment by cescoffier** [comment]
Yes, that would work!

**Comment by dmlloyd** [comment]
> certificate-generator -> io.smallrye.certs.generator maybe?

The module contains the following packages:

* `io.smallrye.certs`
* `io.smallrye.certs.ca`
* `io.smallrye.certs.chain`

Normally I'd be hesitant to have a module name not be aligned with the package name. Are these packages at risk for a split package problem with some other future module? Should the packages be renamed?
